version: "3.9"
services:
  mediary-api-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - mediary-network
networks:
  mediary-network:
    name: mediary-network
    
    